FROM node:18.16.0-alpine

#Install some dependencies
RUN apk add --update git
WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install

# Build sync server to anonimous volume (for ota updates)
RUN npm start tec/server/start
VOLUME ["/usr/app/tec/server/start/-/"]

CMD node ./tec/server/start/-/node.js sync=9090
