FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY scada /scada

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /scada
#USER appuser

WORKDIR /scada
ENV FLASK_DEBUG=1
CMD ["python", "scada.py"]

EXPOSE 6069
