FROM node:18.16.0-alpine

#Install some dependencies
RUN apk add --update git
WORKDIR /usr/app
COPY ./ /usr/app
RUN npm install

# Build sync server to anonimous volume (for ota updates)
VOLUME ["/usr/app/tec/power/service/start/-/"]
RUN npm start tec/power/service/start

CMD node ./tec/power/service/start/-/node.js \
	sync=9092 \
	masters=ws://172:28:1:1:9090
