FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY plc /plc

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /plc
#USER appuser

WORKDIR /plc
CMD ["python", "plc.py"]

EXPOSE 6064