FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY sensors /sensors

WORKDIR /sensors
CMD ["python", "sensors.py"]
EXPOSE 6068